import { formatLanguages } from "../utils/repositoryAnalytics";

const GITHUB_API_BASE_URL = "https://api.github.com";
const COMMIT_ACTIVITY_RETRY_DELAY_MS = 1000;
const COMMIT_ACTIVITY_RETRY_LIMIT = 5;

function wait(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

function getWeekStartTimestamp(dateString) {
  const date = new Date(dateString);
  date.setHours(0, 0, 0, 0);
  date.setDate(date.getDate() - date.getDay());

  return Math.floor(date.getTime() / 1000);
}

function formatRecentCommitsAsWeeklyActivity(commits) {
  const weeklyTotals = new Map();

  commits.forEach((item) => {
    const commitDate = item.commit?.committer?.date || item.commit?.author?.date;

    if (!commitDate) {
      return;
    }

    const week = getWeekStartTimestamp(commitDate);
    weeklyTotals.set(week, (weeklyTotals.get(week) || 0) + 1);
  });

  return Array.from(weeklyTotals.entries())
    .sort(([weekA], [weekB]) => weekA - weekB)
    .map(([week, total]) => ({
      week,
      total,
    }));
}

async function fetchJson(url, errorMessage) {
  const response = await fetch(url);
  const data = await response.json();

  if (!response.ok) {
    throw new Error(errorMessage);
  }

  return data;
}

export async function fetchRepository(owner, repo) {
  return fetchJson(`${GITHUB_API_BASE_URL}/repos/${owner}/${repo}`, "Repository Not Found");
}

export async function fetchLanguages(owner, repo) {
  const languageData = await fetchJson(
    `${GITHUB_API_BASE_URL}/repos/${owner}/${repo}/languages`,
    "Failed to fetch language data"
  );

  return formatLanguages(languageData);
}

export async function fetchCommitActivity(owner, repo) {
  for (let attempt = 0; attempt <= COMMIT_ACTIVITY_RETRY_LIMIT; attempt += 1) {
    const response = await fetch(
      `${GITHUB_API_BASE_URL}/repos/${owner}/${repo}/stats/commit_activity`
    );

    if (response.status !== 202) {
      const activityData = await response.json();

      if (!response.ok) {
        throw new Error("Failed to fetch commit activity");
      }

      if (!Array.isArray(activityData)) {
        throw new Error("Invalid commit activity data returned by GitHub");
      }

      return activityData;
    }

    if (attempt < COMMIT_ACTIVITY_RETRY_LIMIT) {
      await wait(COMMIT_ACTIVITY_RETRY_DELAY_MS);
    }
  }

  const commitsData = await fetchJson(
    `${GITHUB_API_BASE_URL}/repos/${owner}/${repo}/commits?per_page=100`,
    "Commit activity is still being generated by GitHub. Please try again shortly."
  );

  if (!Array.isArray(commitsData)) {
    throw new Error("Invalid commits data returned by GitHub");
  }

  return formatRecentCommitsAsWeeklyActivity(commitsData);
}
